### ISSUE TITLE
Error: ENOENT: no such file or directory, lstat 'node_modules\ember-highcharts\node_modules'

### ISSUE THREAD

**Issue by nagkumar** [gregjopa/ember-reporting-dashboard#1]
I see this error on ember server.. tired to install 'npm install ember-highcharts' but same issue is seen.. looks like some more pre-requisites are missing as not sure how node_modules\ember-highcharts\node_modules would really exists as ember-highcharts itself is a npm module

C:\temp\js\ember-reporting-dashboard>ember server
version: 1.13.13
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
ENOENT: no such file or directory, lstat 'C:\temp\js\ember-reporting-dashboard\node_modules\ember-highcharts\node_modules'
Error: ENOENT: no such file or directory, lstat 'C:\temp\js\ember-reporting-dashboard\node_modules\ember-highcharts\node_modules'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at Object.realpathSync (fs.js:1522:21)
    at symlinkWindows (C:\temp\js\ember-reporting-dashboard\node_modules\symlink-or-copy\index.js:87:26)
    at symlinkOrCopySync (C:\temp\js\ember-reporting-dashboard\node_modules\symlink-or-copy\index.js:56:5)
    at C:\temp\js\ember-reporting-dashboard\node_modules\broccoli-plugin\read_compat.js:58:9
    at lib$rsvp$$internal$$tryCatch (C:\temp\js\ember-reporting-dashboard\node_modules\rsvp\dist\rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (C:\temp\js\ember-reporting-dashboard\node_modules\rsvp\dist\rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (C:\temp\js\ember-reporting-dashboard\node_modules\rsvp\dist\rsvp.js:476:11)
    at lib$rsvp$asap$$flush (C:\temp\js\ember-reporting-dashboard\node_modules\rsvp\dist\rsvp.js:1198:9)

**Comment by gregjopa** [comment]
What version of node and npm are you using?

There is an open issue with the ember-highcharts addon with npm v3: https://github.com/ahmadsoe/ember-highcharts/pull/45

**Comment by gregjopa** [comment]
This issue with npm3 should be resolved. I updated this repo to the latest version of ember-highcharts (0.3.0) which fixes this issue.
